working version
apostrophecms/csv-to-zone-file pull request #1
Opened 2021-11-05 14:55 UTC by boutell

2021-11-05 14:56 UTC, boutell commented on app.js
> +function parse (input) {
I've used this snippet in a couple places lately.

2021-11-05 15:44 UTC, abea requested changes
A few notes in preparation for publishing

2021-11-05 15:44 UTC, abea commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
If it's under the apostrophe banner I think we should add our linter in here at least.

2021-11-05 15:44 UTC, abea commented on README.md
> +`Type`
It'd be nice to have this in a table structure for easy parsing.

2021-11-08 14:34 UTC, boutell commented
eslint testing set up, and reformatted README.

2021-11-08 14:49 UTC, abea approved these changes

2021-11-08 15:49 UTC, merged